/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @name polyfea-context
     * /**
     * @description This component uses the Polyfea interface to load a context area, dynamically render its elements, 
     * and load the resources for the associated microfrontend before rendering the elements. 
     * If the context area cannot be retrieved or it has no elements, the slotted content is displayed instead.
     * @remarks For more details on the ContextArea type, refer to the
     * @polyfea /browser-api package documentation. 
     * The path for context area requests is relative to document.baseURI.
     */
    interface PolyfeaContext {
        /**
          * Defines additional attributes to be set on the rendered elements.   The attributes are set in the following order:  1. The `context` attribute, with its value set to the `name` property. 2. The attributes defined in the element specification of the context area. 3. The attributes defined in this property.
         */
        "extraAttributes": { [key: string]: string };
        /**
          * Additional style properties to be set on the rendered elements.   The style properties are set in the following order:  1. Style properties defined in the element specification of the context area. 2. Style properties defined in this property.
         */
        "extraStyle": { [key: string]: string | number };
        /**
          * name of the context area to load.
         */
        "name": string;
        /**
          * Specifies the number of context area elements to render.  If this property is unset or has a non-positive value, all elements will be rendered.
         */
        "take": number;
    }
}
declare global {
    /**
     * @name polyfea-context
     * /**
     * @description This component uses the Polyfea interface to load a context area, dynamically render its elements, 
     * and load the resources for the associated microfrontend before rendering the elements. 
     * If the context area cannot be retrieved or it has no elements, the slotted content is displayed instead.
     * @remarks For more details on the ContextArea type, refer to the
     * @polyfea /browser-api package documentation. 
     * The path for context area requests is relative to document.baseURI.
     */
    interface HTMLPolyfeaContextElement extends Components.PolyfeaContext, HTMLStencilElement {
    }
    var HTMLPolyfeaContextElement: {
        prototype: HTMLPolyfeaContextElement;
        new (): HTMLPolyfeaContextElement;
    };
    interface HTMLElementTagNameMap {
        "polyfea-context": HTMLPolyfeaContextElement;
    }
}
declare namespace LocalJSX {
    /**
     * @name polyfea-context
     * /**
     * @description This component uses the Polyfea interface to load a context area, dynamically render its elements, 
     * and load the resources for the associated microfrontend before rendering the elements. 
     * If the context area cannot be retrieved or it has no elements, the slotted content is displayed instead.
     * @remarks For more details on the ContextArea type, refer to the
     * @polyfea /browser-api package documentation. 
     * The path for context area requests is relative to document.baseURI.
     */
    interface PolyfeaContext {
        /**
          * Defines additional attributes to be set on the rendered elements.   The attributes are set in the following order:  1. The `context` attribute, with its value set to the `name` property. 2. The attributes defined in the element specification of the context area. 3. The attributes defined in this property.
         */
        "extraAttributes"?: { [key: string]: string };
        /**
          * Additional style properties to be set on the rendered elements.   The style properties are set in the following order:  1. Style properties defined in the element specification of the context area. 2. Style properties defined in this property.
         */
        "extraStyle"?: { [key: string]: string | number };
        /**
          * name of the context area to load.
         */
        "name"?: string;
        /**
          * Specifies the number of context area elements to render.  If this property is unset or has a non-positive value, all elements will be rendered.
         */
        "take"?: number;
    }
    interface IntrinsicElements {
        "polyfea-context": PolyfeaContext;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @name polyfea-context
             * /**
             * @description This component uses the Polyfea interface to load a context area, dynamically render its elements, 
             * and load the resources for the associated microfrontend before rendering the elements. 
             * If the context area cannot be retrieved or it has no elements, the slotted content is displayed instead.
             * @remarks For more details on the ContextArea type, refer to the
             * @polyfea /browser-api package documentation. 
             * The path for context area requests is relative to document.baseURI.
             */
            "polyfea-context": LocalJSX.PolyfeaContext & JSXBase.HTMLAttributes<HTMLPolyfeaContextElement>;
        }
    }
}
